### ISSUE TITLE
Issue with options / make script

### ISSUE THREAD

**Issue by bondhugula** [flame/blislab#1]
A couple of things I noticed while I was trying this out.

1) The makefile includes are still using '-openmp' with Intel's compilers. '-openmp' was deprecated some time back, and is no longer supported (at least with icc version 19.0.x). 
-openmp -> -qopenmp

2) At step4/makefile:33, the command is broken (multiple args to 'cd')

cd $(BLISLAB_DIR)/test && $(MAKE) && cd $(BLISLAB_DIR) $(LDFLAGS)

and similarly, other 'makefile's in the other directories.

**Comment by jianyuh** [comment]
Thanks @bondhugula for pointing this out! Will update this soon.

**Comment by jianyuh** [comment]
Fixed with https://github.com/flame/blislab/pull/3.
